export const regions: Record<string, string> = {
	American: 'US',
	British: 'GB',
	Canadian: 'CA',
	Chinese: 'CN',
	Croatian: 'HR',
	Dutch: 'NL',
	Egyptian: 'EG',
	Filipino: 'PH',
	French: 'FR',
	Greek: 'GR',
	Indian: 'IN',
	Irish: 'IE',
	Italian: 'IT',
	Jamaican: 'JM',
	Japanese: 'JP',
	Kenyan: 'KE',
	Malaysian: 'MY',
	Mexican: 'MX',
	Moroccan: 'MA',
	Polish: 'PL',
	Portuguese: 'PT',
	Russian: 'RU',
	Spanish: 'ES',
	Thai: 'TH',
	Tunisian: 'TN',
	Turkish: 'TR',
	Ukrainian: 'UA',
	Unknown: 'ZZ',
	Vietnamese: 'VN',
};
export const regionsArray = [
	{ strArea: 'American', code: 'US' },
	{ strArea: 'British', code: 'GB' },
	{ strArea: 'Canadian', code: 'CA' },
	{ strArea: 'Chinese', code: 'CN' },
	{ strArea: 'Croatian', code: 'HR' },
	{ strArea: 'Dutch', code: 'NL' },
	{ strArea: 'Egyptian', code: 'EG' },
	{ strArea: 'Filipino', code: 'PH' },
	{ strArea: 'French', code: 'FR' },
	{ strArea: 'Greek', code: 'GR' },
	{ strArea: 'Indian', code: 'IN' },
	{ strArea: 'Irish', code: 'IE' },
	{ strArea: 'Italian', code: 'IT' },
	{ strArea: 'Jamaican', code: 'JM' },
	{ strArea: 'Japanese', code: 'JP' },
	{ strArea: 'Kenyan', code: 'KE' },
	{ strArea: 'Malaysian', code: 'MY' },
	{ strArea: 'Mexican', code: 'MX' },
	{ strArea: 'Moroccan', code: 'MA' },
	{ strArea: 'Polish', code: 'PL' },
	{ strArea: 'Portuguese', code: 'PT' },
	{ strArea: 'Russian', code: 'RU' },
	{ strArea: 'Spanish', code: 'ES' },
	{ strArea: 'Thai', code: 'TH' },
	{ strArea: 'Tunisian', code: 'TN' },
	{ strArea: 'Turkish', code: 'TR' },
	{ strArea: 'Ukrainian', code: 'UA' },
	{ strArea: 'Vietnamese', code: 'VN' },
];
export const letters = [
	'A',
	'B',
	'C',
	'D',
	'E',
	'F',
	'G',
	'H',
	'I',
	'J',
	'K',
	'L',
	'M',
	'N',
	'O',
	'P',
	'Q',
	'R',
	'S',
	'T',
	'U',
	'V',
	'W',
	'X',
	'Y',
	'Z',
];
